server:
  port: 5000
spring:
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database: POSTGRESQL
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    platform: postgres
    url: ${DB_URL:changeit}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:changeit}
    password: ${DB_PASSWORD:changeit}
  redis:
    host: ${REDIS_HOST:changeit}
    port: ${REDIS_PORT:changeit}